service: sls-discord-notifier

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1

functions:
  index:
    handler: index.handler
    description: Message specific channel each time a file was uploaded to S3 bucket.
    events:
      - s3:
          bucket: sls-trigger-bucket
          event: s3:ObjectCreated:*
    environment:
      DISCORD_WEBHOOK_ID: YOUR_DISCORD_WEBHOOK_ID
      DISCORD_WEBHOOK_TOKEN: YOUR_DISCORD_WEBHOOK_TOKEN